package Sort;

public enum SortType {
    PRIMARY_CUISINE_PRIMARY_COST_BRACKET,
    PRIMARY_CUISINE_PRIMARY_COST_BRACKET_RATING_GREATER_EQUAL_4,
    PRIMARY_CUISINE_SECONDARY_COST_BRACKET_RATING_GREATER_EQUAL_4_5,
    SECONDARY_CUISINE_PRIMARY_COST_BRACKET_RATING_GREATER_EQUAL_4_5,
    TOP_4_NEW_RESTAURANT_BY_RATING,
    PRIMARY_CUISINE_PRIMARY_COST_RATING_LESS_4,
    PRIMARY_CUISINE_SECONDARY_COST_RATING_LESS_4_5,
    SECONDARY_CUISINE_PRIMARY_COST_RATING_LESS_4_5,
    ALL_RESTAURANT_ANY_CUISINE_COST_BRACKET;
}
